security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
        App\Entity\Admin:
            algorithm: bcrypt

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: username

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        admin:
            pattern: ^/admin
            lazy: true
            provider: admin_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout

        main:
            lazy: true
            provider: user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
